### ISSUE TITLE
Small Enhancement to Debian Dockerfile

### ISSUE THREAD

**Issue by dbofmmbt** [zupzup/rust-docker-web#1]
Hello, I saw your blog post in log rocket and I would like to suggest you a small change in Debian Dockerfile.

https://github.com/zupzup/rust-docker-web/blob/62fabdb2678ae5409f909feae3841b769e123a09/debian/Dockerfile#L6-L11

Line 6 generates files (src/main.rs and target/...) which we do not need. Therefore, it's better to remove them in the same layer:

```Dockerfile
RUN cargo build --release \
    && rm src/*.rs target/release/deps/server*
```

This way, we can reduce number of layers. Since it's a multistage build, it won't reduce the final image size, though.

**Comment by zupzup** [comment]
Hey! Thanks for the feedback.

In the above snippet you provided, where would the `ADD. ./` go? Because if it happens before `rm src/*.rs`, we would remove our own source files.

So the issue is, that the build needs to happen before removing the old src, which has to happen before adding the new source. However, the two `rm` statements could probably be combined, as their order shouldn't matter :thinking:

**Comment by dbofmmbt** [comment]
Here's the full change:

```Dockerfile
RUN cargo build --release \
    && rm src/*.rs target/release/deps/rust_docker_web*

ADD . .
```

What do you think?

**Comment by zupzup** [comment]
Hey, that works nicely. I added the change with reference to you, thanks for the contribution!
